name: notification after issue creation
on:
  issues:
    types: [opened]    

jobs:
 sendIssues:
  runs-on: ubuntu-latest
  steps:

  - name: get issues
    id: rel_issues
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.issue) }}
    run: |
      echo $ISSUE_CONTEXT 
