name: auto-upload announcements to website

on:
  discussion:
    types: [created]    

jobs:
 sendAnnouncement:
  runs-on: ubuntu-latest
  steps:

  - name: get release/announcement
    if: github.event.discussion.category.slug == 'general'
    id: rel_annou
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.discussion) }}
    run: |
      echo $ISSUE_CONTEXT

  - name: Get discussion info
    id: info
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.discussion) }}
    run: |
      echo "::set-output name=title::${{ github.event.discussion.title }}"
      echo "::set-output name=description::${{ github.event.discussion.body }}"
      echo "::set-output name=date::$(date +'%Y%m')"
      echo "::set-output name=date_spelled::$(date +'%B %Y')"
  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v1
    with:
      token: ${{ secrets.TEST_GA_TOKEN }}
      repository: ilaria-carlini/test-dispatch
      event-type: announcement_launched
      client-payload: '{"id": "${{ steps.info.outputs.date }}", "title": ${{ steps.info.outputs.title }}, "date": "${{ steps.info.outputs.date_spelled }}", "description": "${{ steps.info.outputs.description }}", "image": "???", "type" : "announcement_launched" }'
