name: Auto-upload Distro announcements to Bazaar

on:
  discussion:
    types: [pinned]    

jobs:
 sendAnnouncement:
  runs-on: ubuntu-latest
  if: github.event.discussion.category.name == 'Announcements' || github.event.discussion.category.name == 'Releases' || github.event.discussion.category.name == 'Research news' || github.event.discussion.category.name == 'Schools and crash courses'
  steps:
  
  - name: Fetch announcement
    id: announcement
    run: |
      category="${{ github.event.discussion.category.name }}"
      title="${{ github.event.discussion.title }}"
      body="${{ github.event.discussion.body }}"
      echo "${{ toJson(github.event) }}"
      echo "::set-output name=title::${title}"
      echo "::set-output name=category::${category}"
      echo "::set-output name=description::${body}"
        
  - name: Fetch current date
    id: date
    run: |
        echo "::set-output name=date::$(date +'%Y%m')"
        echo "::set-output name=date_spelled::$(date +'%B %Y')"
  - name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v1.1.3
    with:
      token: ${{ secrets.TEST_GA_TOKEN }}
      repository: ilaria-carlini/test-dispatch
      event-type: announcement_launched
      client-payload: '{"description": "${{ steps.announcement.outputs.description }}", "category": "${{ steps.announcement.outputs.category }}", "id": "${{ steps.date.outputs.date }}", "title": "${{ steps.announcement.outputs.title }}", "date": "${{ steps.date.outputs.date_spelled }}", "image": "???", "type" : "announcement_launched" }'
