name: auto-upload announcements to website

on:
  discussions: 
    types: [created]    

jobs:
 sendAnnouncement:
  runs-on: ubuntu-latest
  steps:

  - name: get release/announcement
    id: rel_annou
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.discussion) }}
    run: |
      echo $ISSUE_CONTEXT 
