name: auto-upload announcements to website

on:
  discussion:
    types: [created]    

jobs:
 sendAnnouncement:
  runs-on: ubuntu-latest
  steps:

  - name: get release/announcement
    if: github.event.discussion.category.slug == "general"
    id: rel_annou
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.discussion) }}
    run: |
      echo $ISSUE_CONTEXT
