name: auto-upload announcements to website

on:
  discussion:
    types: [created]    

jobs:
 sendAnnouncement:
  runs-on: ubuntu-latest
  steps:

  - name: get release/announcement
    if: github.event.discussion.category.slug == 'general'
    id: rel_annou
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.discussion) }}
    run: |
      echo $ISSUE_CONTEXT

  - name: Get title
    id: title
    env:
      ISSUE_CONTEXT: ${{ toJson(github.event.discussion) }}
    run: |
      echo $ISSUE_CONTEXT > temp_title.txt
      sed -nr 's/.*"title": (.*), "updated.*/\1/p' <temp_title.txt >title.txt
      echo "::set-output name=title::$(cat title.txt)"
      echo "${{ github.event.discussion.title }}"
