name: Repository Dispatch

on:
  repository_dispatch:
    types: [repository_trigger]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello"
